output: docs
clean: true
sdk: iphonesimulator
source_directory: Timber/Classes
exclude: Example/
author: Max Kramer <max@maxkramer.co>
author_url: https://maxkramer.co
module: Timber
copyright: © 2016 Max Kramer
readme: README.md
github_url: https://github.com/MaxKramer/Timber
theme: apple
