language: objective-c
osx_image: xcode7.3
xcode_workspace: Example/Timber.xcworkspace
xcode_scheme: Timber-Example
xcode_sdk: iphonesimulator9.3
cache: bundler

before_install: 
    - rvm install ruby-2.2.2
    - rvm use 2.2.2
install: bundle install --without=documentation
script: make test
after_success: make codecov
